---
title: "TSProject-AutoSales"
author: "Steve Bramhall"
date: "July 26, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tswge)
library(nnfor)
library(vars)
```

```{r}
# read file
data = read.csv(file='TSProject.csv',header=TRUE)
data <- na.omit(data) # remove last row, has NA's
names(data) <- c("Date","AutoSales","ConstSpend","UnempRate") # rename table columns

# plot data
plotts.sample.wge(data$AutoSales)
acf(data$AutoSales[0:100])
acf(data$AutoSales[101:200])
plotts.sample.wge(data$ConstSpend)
acf(data$ConstSpend[0:100])
acf(data$ConstSpend[101:200])
plotts.sample.wge(data$UnempRate)
acf(data$UnempRate[0:100])
acf(data$UnempRate[101:200])

# We know the data is monthly so let's go ahead a remove that seasonality
est.ar.wge(data$AutoSales,p=18)              # overfit    
d12=artrans.wge(data$AutoSales,phi.tr=c(rep(0,11),1))  # remove seasonality
d12.1=artrans.wge(d12,phi.tr=1)      # remove trend
pacf(d12)
salesEst=est.ar.wge(d1.12,p=15,type='burg')  # overfit
salesEst
psi.weights.wge(phi=salesEst$phi,lag.max=5)  # get psi weights




```