---
title: "Time Series Midterm DS6373-403"
author: "Steve Bramhall"
date: "June 29, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tswge)
library(stats)
library(tidyverse)
library(tswgewrapped)
```

```{r Prob1}
x=c(6,8,13,12,10,7,4,2)
gamma0=var(x)*((length(x)-1)/length(x)) # gamma0 = variance*(7/8)
```

```{r Prob2}
autocorr=acf(x,lag.max=length(x)-1)
autocorr
```

```{r Prob3}
# counted x0,X3 x1,x4 x2,x5 x3,x6 x4,x7 x5,x8 
# 6 pairs = n - 3
```

```{r Prob4}
# for rho7: 1,8 2,6 
```

```{r Prob6}
# (1-.6B+.4B^2)
psi.weights.wge(phi=c(.6,-.4),lag.max=length(x)-1)

# xt = at + psi1_t-1 + psi2_t-2 + psi3_t-3
# xt = at + .6t-1 - .04t-2 - .264t-3


gen.arma.wge(n=100,phi=-.5,sn=7)
plotts.true.wge(n=100,phi=-.5)
```

```{r Prob 7}
x=gen.arma.wge(100,phi=c(.6,-.4))
psi.weights.wge(phi=c(.6,-.4),lag.max=length(x)-1)

```


```{r Prob 8}
# a = observed - estimated
```

```{r Prob 9}
fore.arma.wge(x,phi=c(.6,-.4),n.ahead=4)
```

```{r Prob 29}
data("global.temp")
gt = global.temp[100:length(global.temp)]

modsn = fore.sigplusnoise.wge(gt,n.ahead=10, lastn=T)
ASE1 = mean((modsn$f - gt[(61-9):61])^2)
ASE1

mod2 = fore.aruma.wge(gt,phi=c(-.62,.06,-.31),d=1,theta=c(-.17,-.75),n.ahead=10,lastn=T)
ASE2 = mean((mod2$f - gt[(61-9):61])^2)
ASE2

```



```{r}

# (1-.4B+.6B^2-.8B^3)(X_t-9)=a_t
psi.weights.wge(phi=c(.4,-.6,.8),lag.max = 5)

# arma forecast with CV
data = read.csv(file='',header=TRUE)  # load files
plotts.wge(data$col)                  # plot data
arma1 = fore.armu.wge(data$col,phi=c(),n.ahead=39,lastn=T,limits=F)
aramASE1 = mean((arama1$f - data$col[69:99])^2)

# aruma forecst with cv
# (B)(1-B^12)(X_t - u) = a_t
# flat, last value, no trend
aruma1=fore.aruma.wge(data2=0,s=12,phi=c(.74,0,0,0,0,0,0,0,0,0,0,.38,-.2812),n.ahead=36,lastn=T,limits=F)
arumaASE1 = mean((arama1$f - data$col[69:99])^2)

# signal plus noise forecast with CV
sgdata=gen.sigplusnoise.wge(n=50,b0=10,b1=.2,phi=c(.8,-.6))
sg1=fore.sigplusnoise.wge(sgdata,linear=T,n.ahead=20,lastn=F,limits=F)
sg1ASE1 = mean((sgdata$f - sgdata[xx,xx])^2)


```


Half Widths
```{r For Live Session}
x=c(5,8,9,8,7,6,4,3)
mult.wge(.9,.8)
sdx=sd(x)
psiw=psi.weights.wge(phi=c(1.7,-.72),lag.max = 5)
fore.aruma.wge(x,phi=c(1.7,-.72),n.ahead=3,plot=T,limits=T)
psiw0=1;
halfw1=1.96*sdx*((psiw0^2)^.5)
halfw2=1.96*sdx*(((psiw0^2)+(psiw[1]^2))^.5)
halfw3=1.96*sdx*(((psiw0^2)+(psiw[1]^2)+(psiw[2]^2))^.5)
halfw1
halfw2
halfw3
```

```{r}
factor.wge(phi=c(-.1,.3))
x=gen.arma.wge(n=100,phi=c(-.1,.3))
plotts.sample.wge(x)
```

```{r p1}
x = c(6, 8, 13, 12, 10, 7, 4, 2, 1)
mean(x)
n=9
gamma0=var(x)*(n-1)/n 
n=5
gamma0 = var(x)*(n-1)/n
paste("pred yo =", gamma0)
aut=acf(x,lag.max=n-1,plot=FALSE)
aut
psiw=psi.weights.wge(phi=c(.6,-.4),lag.max = 5)
psiw
f=fore.aruma.wge(x,phi=c(.6,-.4),n.ahead=3,plot=T,limits=T)
f$wnv^2
```

```{r}
data(global.temp)
plot(global.temp)
gt=global.temp[100:length(global.temp)]
length(gt)
sign=fore.sigplusnoise.wge(gt,linear=T,n.ahead=10,lastn=T,limits=F)
ASE1 = mean((sign$f-gt[51:60])^2)
ASE1

mod2=gen.aruma.wge(n=60,phi=c(-.62,.06,-.31),d=1,theta=c(-.17,-.75))
mod2b=artrans.wge(mod2,c(1))
mod2c=fore.aruma.wge(mod2b,phi=c(-.62,.06,-.31),d=1,theta=c(-.17,-.75),n.ahead=20,limits=T)

ASE2 = mean((mod2c$f-gt[51:60])^2)
ASE2

```

```{r Breakout 5}
x = gen.arma.wge(100,phi=c(.723,.283,-.519),theta=-.6)
plotts.sample.wge(x)
f1=fore.arma.wge(sunspot.year,phi=c(.723,.283,-.519),theta=-.6,n.ahead=20,lastn=T, limits=F)
ASE1 = mean(sunspot.month[289-20+1]:289-f1$f)^2
ASE1

x=gen.aruma.wge(100,d=1,s=12)
plotts.sample.wge(x)
f2=fore.aruma.wge(sunspot.year,d=1, s=12, n.ahead=20,lastn=T,limits=F)
ASE2 = mean((sunspot.year[289-19]-f2$f)^2)
ASE2

x=gen.aruma.wge(100,phi=c(1.06,-.4),s=10)
plotts.sample.wge(x)
f3=fore.aruma.wge(sunspot.year,phi=c(1.06,-.4),s=10,n.ahead=20,lastn=T,limits=F)
ASE3 = mean((sunspot.year[289-19]-f3$f)^2)
ASE3

```

```{r Pg 245-6 Ex 6.2}
# half width = MOE

# (1 - .9B)Xt = at

x=gen.arma.wge(1000,phi=.9,sn=1)                       # generate waveform
estAR1 = est.arma.wge(x,p=1)                           # get estimated phi's, we know it's an AR 1 so p=1
preds=fore.arma.wge(x,phi=estAR1$phi,n.ahead=50)       # forecast with estimated phi's to get wnv
preds
psi.weights.wge(phi=estAR1$phi, lag.max=10)            # check the psi weights from the estimated phi

# all psi weights
MOE = 1.96*sqrt(preds$wnv)*sqrt(sum(c(1,preds$psi^2))) # calc margin or error

# for first limits
MOE_1 = 1.96*sqrt(preds$wnv)
preds$f[1] + MOE_1 # ul
preds$f[1] - MOE_1 # ll

# for 2nd limits
MOE_2 = 1.96*sqrt(preds$wnv)*sqrt(1^2+preds$psi[1]^2)
preds$f[2] + MOE_2 # ul
preds$f[2] - MOE_2 # ll

#confirm
preds$ll[2]
preds$ul[2]

# psi weights are only used in the GLP form (linear combo of wn terms and the coefs of the wn terms are the psi weights)

```


```{r Book Prob 3.6}
# (Xt - X_t-1 + .26X_t-2 + .64X_t-3 - .576X_t-4 = at - 2.4a_t-1 + 2.18a_t-2 - .72a_t-3)

# AR portion
factor.wge(phi=c(1,-.26,-.64,.576))

# MA portion
factor.wge(phi=c(2.4,-2.18,.72))

# -> (1-1B+.9B^2)(1-.8B)(1+.8B) = (1-1.6B+.9B^2)(1-.8B) -> AR(4,3)
# since there's a (1-.8B) term on both sides, they cancel
# -> (1-1B+.9B^2)(1+.8B) = (1-1.6B+.9B^2) -> AR(3,2)

# invertibilty refers to whether all roots of the MA portion have an Abs Recip < 1
# stationarity refers to whether all roots of the AR portion have an Abs Recip < 1 ? 
```

```{r Book Prob 3.7a}
# a. (Xt - .1X_t-1 + .5X_t-2, + .08X_t-3 - .24X_t-4) = at  -> AR(4)
factor.wge(phi=c(.1,-.5,-.08,.24))
# i. yes, stationary since all Abs Recip < 1
# ii. yes, since the process is AR and stationary with all Abs Recip < 1 (roots outside unit circle)
# iii. 
plotts.true.wge(phi=c(.1,-.5,-.08,.24))
```

```{r Book Prob 3.7b}
# b. (Xt - 1.3X_t-1 + .4X_t-2) = at - 1.9a_t-1  -> ARMA(2,1)
factor.wge(phi=c(1.3,-.4))
factor.wge(phi=c(1.9))
# i. yes, stationary since all Abs Recip < 1 for the AR portion
# ii. no, not invertible since Abs Recip > 1 for the MA portion
# iii. 
plotts.true.wge(phi=c(1.3,-.4),theta=1.9)

```

```{r Midterm Bonus Find Invertible Model}
# Xt = (1 + .17B + 2.75B^2) = at
factor.wge(phi=c(-.17,-2.75))

theta1=2*(-.0309)
theta2=-((-.0309)^2 + .6022^2)
plotts.true.wge(theta=c(theta1,theta2))$aut1
plotts.true.wge(theta=c(-.17,-2.75))$aut1
theta1
theta2
```

```{r Book Prob 5.1}
data("hadley")

# b. Use the least squares method, fit a linear regression line to the data
t = 1:160
lm(hadley ~ t) # shows a=.00438 and b = -.525737

# c. Calc the residuals
hadely.resid = hadley+.525737-.004438*t
plotts.wge(hadely.resid)
```

