---
title: "Prelive Unit12"
author: "Steve Bramhall"
date: "July 21, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tswge)
library(vars)
library(RColorBrewer)
```

```{r Prob1}
data = read.csv("la_cmort_study.csv", header=T)

# corr matrix
library(tidyverse)
ggpairs(data[,2:4])

# plot the temp
plotts.sample.wge(data$temp)
acf(data$temp[1:254])    # acf stationarity check
acf(data$temp[255:508])  # acf stationarity check

# plot the pollution
plotts.sample.wge(data$part)
acf(data$part[1:254])    # acf stationarity check
acf(data$part[255:508])  # acf stationarity check

# plot the cardica mortality
plotts.sample.wge(data$cmort)
acf(data$cmort[1:254])   # acf stationarity check
acf(data$cmort[255:508]) # acf stationarity check

# test/train split
train.temp=ts(data$temp[0:488])
test.temp=ts(data$temp[489:508])
train.part=ts(data$part[0:488])
test.part=ts(data$part[489:508])
train.cmort=ts(data$cmort[0:488])
test.cmort=ts(data$cmort[489:508])

### should've differenced the data due to the weekly seasonality
# artrans.wge(data$temp,c(rep(0,51),1))
### can also capture seasonality by adding a different mean per week


# cross-correlation functions
ccf(train.temp, train.cmort,ylim=c(-1,1)) # corr at lag1
ccf(train.part, train.cmort,ylim=c(-1,1)) # corr at lag4

# create and add lagged variables to data
train.tempL1 = c(NA,train.temp[1:length(train.temp)-1])            # temp lagged once
train.partL4 = c(rep(NA,4),train.part[(1:(length(train.part)-4))]) # part lagged 4

# 2nd way to lag if data is not a time series
#tempL1=dplyr::lag(train.temp,1)
#partL4=dplyr::lag(train.part,4)

train.tempL1 = ts(train.tempL1)  # add new lag to train data
train.partL4 = ts(train.partL4)  # add new lag to train data

# multiple regression fit with lagged variables
fit1 = lm(train.cmort~train.tempL1+train.partL4)
summary(fit1) # check if variables are significant

# get order of residuals
phi=aic.wge(fit1$residuals, p=0:12,q=0, type="bic")
phi # AIC pick p=2

# model residuals to get std errors
residfit1 = arima(train.cmort,order=c(phi$p,0,0),xreg=cbind(train.tempL1,train.partL4))
residfit1

# validate visually & with ljung-box test
acf(residfit1$residuals[8:408])             # plotted residuals show up as white
ltest = ljung.wge(residfit1$resid)
ltest$pval                                   # FTR the null that coefs are 0, so serially correlated
ltest2 = ljung.wge(residfit1$resid,K=48)
ltest2$pval

# forecast
preds = predict(residfit1,newxreg=data.frame(test.temp,test.part))
preds        
plot(seq(1,508,1),data$cmort,type="l")
points(seq(489,508,1),preds$pred,type="b",pch=15,col='blue')

ASE1=mean((test.cmort[1:20]-preds$pred[1:20])^2)
ASE1


# --- Add Time ---
# Add time trend to model (t)
t=1:488
# multiple regression fit
fit2 = lm(train.cmort~t+train.tempL1+train.partL4)

# get order of residuals
phi=aic.wge(fit2$residuals,p=0:12,q=0)
phi # AIC picks p=2

# model residuals to get std errors
residfit2 = arima(train.cmort,order=c(phi$p,0,0),xreg=cbind(t,train.tempL1,train.partL4))
residfit2

# validate visually & with ljung-box test
acf(residfit2$residuals[5:488])             # plotted residuals show up as white
ltest = ljung.wge(residfit2$resid)
ltest$pval                                  # FTR the null that coefs are 0, so serially correlated
ltest2 = ljung.wge(residfit2$resid,K=48)
ltest2$pval

# forecast
preds2 = predict(residfit2,newxreg=data.frame(t=c(489:508),test.temp,test.part))
preds2        
plot(seq(1,508,1),data$cmort,type="l")
points(seq(489,508,1),preds2$pred,type="b",pch=15,col='blue')

ASE2=mean((test.cmort[1:20]-preds2$pred[1:20])^2)
ASE2

# --- Try VAR Model ---
library(vars)
# combine variables
X=cbind(train.cmort,train.temp,train.part)

VARselect(X, lag.max = 15, type = "const", season = NULL, exogen = NULL) 
# VARselect picks p=12 using AIC
# VARselect picks p=2  using BIC


#### Has an option season = 52

# Estimate the coefs
lsfit=VAR(X,p=2,type='const')
lsfit

# Get predictions
preds3=predict(lsfit,n.ahead=20)
preds3        # CIs are Margin of Errors 
preds3$fcst
predVAR=preds3$fcst$train.cmort[1:20,1]

# Calc ASE
ASE3=mean((test.cmort-predVAR)^2)
ASE3

# plot the data
plot(seq(1,508,1),data$cmort,type="l")
points(seq(489,508,1),predVAR,type="b",pch=15,col='blue')

# fan chart using RColorBrewer
fanchart(preds3, colors=brewer.pal(n=8,name="Blues"))

```

```{r Prob2}
BSales = read.csv("businesssales.csv", header=T)

# plot the sales
plotts.sample.wge(BSales$sales)
acf(BSales$sales[1:50])    # acf stationarity check
acf(BSales$sales[51:100])  # acf stationarity check

# plot the ad_tv
plotts.sample.wge(BSales$ad_tv)
acf(BSales$ad_tv[1:50])    # acf stationarity check
acf(BSales$ad_tv[51:100])  # acf stationarity check

# plot the ad_online
plotts.sample.wge(BSales$ad_online)
acf(BSales$ad_online[1:50])    # acf stationarity check
acf(BSales$ad_online[51:100])  # acf stationarity check

# plot the ad_online
plotts.sample.wge(BSales$discount)
acf(BSales$discount[1:50])    # acf stationarity check
acf(BSales$discount[51:100])  # acf stationarity check

# cross-correlation functions
ccf(BSales$ad_tv, BSales$sales,ylim=c(-1,1))     # corr at lag1
ccf(BSales$ad_online, BSales$sales,ylim=c(-1,1)) # corr at lag1
ccf(BSales$discount, BSales$sales,ylim=c(-1,1))  # corr at lag4

# train/test split, set to time series data
train.sales=ts(BSales$sales[0:95])
test.sales=ts(BSales$sales[96:100])
train.adtv=(BSales$ad_tv[0:95])
test.adtv=ts(BSales$ad_tv[96:100])
train.adonline=(BSales$ad_online[0:95])
test.adonline=ts(BSales$ad_online[96:100])
train.discount=(BSales$discount[0:95])
test.discount=ts(BSales$discount[96:100])

# create and add lagged variables to data
tvadL1=dplyr::lag(train.adtv,1)
onlineadL1=dplyr::lag(train.adonline,1)
discountL4=dplyr::lag(train.discount,4)

# add new lag to train data
train.adtvL1 = ts(tvadL1)          
train.adonlineL1 = ts(onlineadL1)  
train.discountL4 = ts(discountL4)

# multiple regression fit
fit1 = lm(train.sales~train.adtvL1+train.adonlineL1+train.discountL4)

# get order of residuals
aic.wge(fit1$residuals,p=0:12,q=0:5)
phi # AIC pick p=7



# add time
t=1:95
fit2 = lm(train.sales~t+train.adtvL1+train.adonlineL1+train.discountL4)
phi2=aic.wge(fit2$residuals,p=0:12,q=0)
phi2 # AIC pick p=7


# model residuals to get std errors
residfit1 = arima(train.sales,order=c(phi$p,0,0),xreg=cbind(train.adtvL1,train.adonlineL1,train.discountL4))
residfit1

# w/ time
residfit2 = arima(train.sales,order=c(phi$p,0,0),xreg=cbind(t,train.adtvL1,train.adonlineL1,train.discountL4))
residfit2


# validate visually & with ljung-box test
acf(residfit2$residuals[5:95])             # plotted residuals show up as white
ltest = ljung.wge(residfit2$resid)
ltest$pval                                   # FTR the null that coefs are 0, so serially correlated
ltest2 = ljung.wge(residfit2$resid,K=48)
ltest2$pval

# forecast
preds1 = predict(residfit2,newxreg=data.frame(t=c(96:100),test.adtv,test.adonline,test.discount))
preds1        
plot(seq(1,100,1),BSales$sales,type="b")
points(seq(96,100,1),preds1$pred,type="b",pch=15)

ASE1=mean((BSales$sales[96:100]-preds1$pred)^2)
ASE1


# --- VAR Model ---
# combine variables
X=cbind(train.sales,train.adtv,train.adonline,train.discount)

VARselect(X, lag.max = 12, type = "const", season = NULL, exogen = NULL) 
# VARselect picks p=3 (using AIC)

# Estimate the coefs
lsfit=VAR(X,p=3,type='const')
lsfit

# Get predictions
preds2=predict(lsfit,n.ahead=5)
preds2       # CIs are Margin of Errors 
preds2$fcst
preds2$fcst$train.sales
predVAR=preds2$fcst$train.sales[1:5,1] # get 1-5 from the 1st row

# Calc ASE
ASE2=mean((BSales$sales[96:100]-predVAR)^2)
ASE2

# plot the data
plot(seq(1,100,1),BSales$sales,type="b")
points(seq(95,100,1),preds2$fcst$train.sales[1:5,1],type="b",pch=15)


# fan chart using RColorBrewer
fanchart(preds2, colors=brewer.pal(n=8,name="Blues"))


```

