---
title: "Practice"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tswge)
```

```{r 1p7}
data(noctula)
data(lavon)

par(mfrow=c(1,2))
plot(1:length(noctula),noctula,type="l")
plot(1:length(lavon),lavon,type="l")

par(mfrow=c(2,2))
acf(noctula[1:48])
acf(noctula[49:96])

acf(lavon[1:56])
pacf(lavon[57:112])
```

```{r 1p8}
data(whale)

par(mfrow=c(1,2))
plot(1:length(whale),whale,type="l")

par(mfrow=c(2,2))
acf(whale[1:143])
acf(whale[144:286])

bonds <- read.csv("10_year_bond_rate_2010-2015.csv")
plot(1:length(bonds$Close),bonds$Close,type="l")
acf(bonds$Close[1:750])
acf(bonds$Close[750:1509])

```

```{r}
xdf=read.csv(file.choose(),header=TRUE)
x=as.numeric(paste(xdf$Adj.Close))
x=x[!is.na(x)]
n=length(x) #n=1509
nlag=2014 #n-1, m=mean(x)
v=var(x,na.rm=TRUE)
gamma0=var(x)*(n-1)/n
aut=acf(x,lag.max=2013) #n-1
sum=0
for (k in 1:nlag) {sum=sum+(1-k/n)*aut$acf[k+1]*gamma0}
vxbar=2*sum/n+gamma0/n #note the mult of sum by 2
vxbar
```


FREQUENCY DOMAIN

```{r}
t = seq(1,100,length=100)
f1=sin(2*pi*0.8*t+5)
plot(t,f1,type="l")
f2=.3*t+10
plot(t,f2,type="l")
f3=f1+f2
plot(t,f3,type="l")
```

