---
title: "Forecasting"
author: "Steve Bramhall"
date: "June 15, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tswge)
```

```{r}
# AR(1) Phi Positive
data(fig6.1nf)
plotts.wge(fig6.1nf)
plotts.sample.wge(fig6.1nf)

# n=how many forecasts ahead do you want to make
fore.arma.wge(fig6.1nf,phi=.8,n.ahead=20,plot=TRUE,limits=FALSE)

# AR(1) Phi Negative
x1 = gen.arma.wge(100, phi=-.8)
fore.arma.wge(x1,phi=-.8,n.ahead = 20,plot=TRUE,limits=FALSE)

# AR(2)
x2=gen.arma.wge(n=75,phi=c(1.6,-.8),sn=24)
# set mean = 25
x2=x2+25
plotts.wge(x2)

fore.arma.wge(x2,phi=c(1.6,-.8),n.ahead=40,limits=TRUE)

# AR(2,1)
x3=gen.arma.wge(n=75,phi=c(1.6,-.8),theta = -.9,sn=24)
fore.arma.wge(x3,phi=c(1.6,-.8),theta=-.9,n.ahead=20,limits=TRUE)

# AR(1,1)
fore.arma.wge(x3,phi=c(.8),theta=-.9,n.ahead=20,limits=TRUE)

```

```{r}
# Canadian Lynx Data

data(llynx)
plotts.wge((llynx))
plotts.sample.wge(llynx)

# AR(4)
fore.arma.wge(llynx,phi=c(1.3,-.7,.1,-.2),n.ahead=20,limits=T)


# AR(4,1)
fore.arma.wge(llynx,phi=c(1.3,-.7,.1,-.2),theta=-.6,n.ahead=20,limits=F)

# AR(11)
fore.arma.wge(llynx,phi=c(1.1676,-.5446,.2662,-.3094,.154,-.1463,.0569,-.0294,.1346,.2021,-.3394),n.ahead=20,limits=F)
```

```{r BLT7p5}
# (1-.967B)(X_t-2.2)=(1+.477)a_t
parms=mult.wge(c(.976),c(2.2))
parms$model.coef
#x4=gen.arma.wge(n=75,phi=parms$model.coef,theta = -.477,sn=24)
x4=gen.arma.wge(n=75,phi=c(.967),theta = -.477,sn=24)
plotts.wge(x4)
fore.arma.wge(x4,phi=c(.967),theta=-.477)

x5=gen.arma.wge(n=100,phi=c(.4411,.0185,-.1193,.0815,-.0003,.0152,.0562,-.094,.0558,.066,.0172,.3685))
fore.arma.wge(x5,phi=c(.4411,.0185,-.1193,.0815,-.0003,.0152,.0562,-.094,.0558,.066,.0172,.3685),theta=-.477,n.ahead=20,limits=T)

```

```{r BLT7p6}
# (1-.4B+.6B^2-.8B^3)(X_t-9)=a_t
psi.weights.wge(phi=c(.4,-.6,.8),lag.max = 5)
s = 1 + .4*.4 + .44*.44
x=gen.arma.wge(n=100,phi=c(.4,-.6,.8))
fore.arma.wge(x,phi=c(.4,-.6,.8),n.ahead=12,lastn=T,limits=F)

### BOOOO
```

```{r Calc Psi Weights}
# psi0 = 1, psi1 = .7, psi2 = .24, psi3 = -.132...
psi.weights.wge(phi=c(1.2,-.6), theta=.5,lag.max = 10)

# (1 - .4B + .6B^2 - .8B^3)(Xt-9)=at
psi.weights.wge(phi=c(.4,-.6,.8),lag.max = 10)

```

```{r Lynx forecast checking with ASE}
data(llynx)
plotts.wge((llynx))

# (1-1.3B + 0.7B^2 - 0.1B^3 + 0.2B^4)(Xt-2.9)=at
x6=fore.arma.wge(llynx,phi=c(1.3,-.7,.1,-.2),n.ahead=12,lastn=T,limits=F)
ASE = mean((x6$f-llynx[103:114])^2)
ASE

# Lynx: AR(4)
LynxF_AR4=fore.arma.wge(llynx,phi=c(1.3,-.7,.1,-.2),n.ahead=30,lastn=T,limits=F)
ASE=mean((LynxF_AR4$f-llynx[85:114])^2)
ASE

# Lynx: AR(11)
LynxF_AR11=fore.arma.wge(llynx,phi=c(1.1676,-.5446,.2662,-.3094,.154,-.1463,.0569,-.0294,.1346,.2021,-.3394),n.ahead=30,limits=F,lastn=T)
ASE=mean((LynxF_AR11$f-llynx[85:114])^2)
ASE
```

```{r}
SWA = read.csv(file='swadelay.csv',header=TRUE)
plotts.wge(SWA$arr_delay)            # plot data
len=length(SWA$arr_delay)                # length of data

# (1 - .44B - .02^2 + 0.12B^3 - 0.08B^4 + 0B^5 - .02B^6 - .06B^7 + .09B^8 -.05B^9 - .07B^10 - .02B^11 - .39B^12)(Xt-34934)=(1+.12B)at
SWA_model1=fore.arma.wge(SWA$arr_delay,phi=c(.44,.02,-.12,.08,0,.02,.06,-.09,.06,.07,.02,.37),n.ahead=30,lastn=T,limits=F)
ASE1 = mean((SWA_model1$f-SWA$arr_delay[148:177])^2)
ASE1

SWA_model2=fore.arma.wge(SWA$arr_delay,phi=c(.34,.07,-.11,.07,.01,.02,.06,-.09,.05,.07,.02,.39),theta=-.12,n.ahead=30,lastn=T,limits=F)
ASE2 = mean((SWA_model2$f-SWA$arr_delay[148:177])^2)
ASE2

```

```{r Prelive}
# (1-.9B)(1-.8B)Xt=at
# (1-1.7B+.72B^2)Xt=at
# x1=5, x2=8, x3=9, x4=8, x5=7, x6=6, x7=4, x8=3
wts_5=psi.weights.wge(phi=c(1.7,-.72),lag.max = 5)
parms=mult.wge(c(1.7,-.72))
parms$model.coef

# (1-.967B)(X_t-2.2)=(1+.477)a_t
parms=mult.wge(c(.976),c(2.2))
parms$model.coef

#x4=gen.arma.wge(n=75,phi=parms$model.coef,theta = -.477,sn=24)
x4=gen.arma.wge(n=75,phi=c(.967),theta = -.477,sn=24)
plotts.wge(x4)
fore.arma.wge(x4,phi=c(.967),theta=-.477)

# Propane
propane <- read.csv("WeeklyPropanePricesPerGallon.csv")
propane <- na.omit(propane)
names(propane) <- c("Date","Price") # rename table columns
plot(1:length(propane$Price),propane$Price,type="l",xlab="Time",ylab="Propane Price per Gallon")
p_est = fore.aruma.wge(propane$Price,n.ahead=30,lastn=T,limits=F,plot=T)
p_est = fore.aruma.wge(propane$Price,phi=c(.8,.1,-.3,-.1,.3),d=2,n.ahead=20,lastn=T,limits=F,plot=T)
p_est
#p_ASE=mean((propane$Price[(1400-30+1):1400]-p_est$f)^2)
#p_ASE
wood = fore.aruma.wge(airlog,d=1,s=12,phi=c(-.36,-.05,-.14,-.11,.04,.09,-.02,.02,.17,.03,-.1,-.38),n.ahead=36,lastn=T,limits=F)

```



```{r Forecast ARIMA}
# ARIMA(0,1,0)
# The forecast = the last value
x=gen.aruma.wge(n=50,phi=.8,d=1,sn=15)
fore.aruma.wge(x,d=1,n.ahead=20,limits=F)

# ARIMA (1,1,0), AR + (1-B) time
# Forecast increases & converges to some value that isn't the mean
x=gen.aruma.wge(n=50,phi=.8,d=1,sn=15)
fore.aruma.wge(x,phi=.8,d=1,n.ahead=20,limits=F)

# ARIMA(0,2,0)
# Forecast follows tread of last 2 data points
x=gen.aruma.wge(n=50,phi=.8,d=1,sn=15)
fore.aruma.wge(x,d=2,n.ahead=20,limits=T)

```

```{r Seaonal Model Forecast}
# (1-B^4)Xt = at
x=gen.aruma.wge(n=20,s=4,sn=6)
fore.aruma.wge(x,s=4,n.ahead=8,lastn=F,plot=T,limits=F)

# turn on last n to check model vs actual
x=gen.aruma.wge(n=20,s=4,sn=6)
fore.aruma.wge(x,s=4,n.ahead=8,lastn=T,plot=T,limits=F)

# (1-.8B)(1-B^4)
x=gen.aruma.wge(n=20,phi=.8,s=4,sn=6)
fore.aruma.wge(x,phi=.8,s=4,n.ahead=8,limits=F)



# airline modes
data(airlog)
# (B)(1-B^12)(X_t - u) = a_t
# flat, last value, no trend
parzen=fore.aruma.wge(airlog,d=0,s=12,phi=c(.74,0,0,0,0,0,0,0,0,0,0,.38,-.2812),n.ahead=36,lastn=T,limits=F)
plotts.sample.wge(airlog)
# (1-B)(1-B^12)(X_t) = a_t
# seasonality and trend continues due to (1-B), d=1
wood = fore.aruma.wge(airlog,d=1,s=12,phi=c(-.36,-.05,-.14,-.11,.04,.09,-.02,.02,.17,.03,-.1,-.38),n.ahead=36,lastn=T,limits=F)
Box_ASE=mean((airlog[(144-36+1):144]-wood$f)^2)
Box_ASE
```

```{r Signal Plus Noise Forecast}
x=gen.sigplusnoise.wge(n=50,b0=10,b1=.2,phi=c(.8,-.6))
xfore=fore.sigplusnoise.wge(x,linear=T,n.ahead=20,lastn=F,limits=F)


```

```{r For Live Session}
x=c(5,8,9,8,7,6,4,3)
mult.wge(.9,.8)
sdx=sd(x)
psiw=psi.weights.wge(phi=c(1.7,-.72),lag.max = 5)
fore.aruma.wge(x,phi=c(1.7,-.72),n.ahead=3,plot=T,limits=T)
psiw0=1;
halfw1=1.96*sdx*((psiw0^2)^.5)
halfw2=1.96*sdx*(((psiw0^2)+(psiw[1]^2))^.5)
halfw3=1.96*sdx*(((psiw0^2)+(psiw[1]^2)+(psiw[2]^2))^.5)
halfw1
halfw2
halfw3

```

```{r AMZN SIGNOISE}
amzn = read.csv(file='AMZN.csv',header=TRUE)
plotts.wge(amzn$Close)             # plot data
fore.sigplusnoise.wge(amzn$Close,linear=T,n.ahead=30,lastn=F,limits=T,plot=T)

```

